# type: ignore
# ruff: noqa
"""

Revision ID: 099fd219f22d
Revises: 634b4cbdd0cf
Create Date: 2026-01-12 15:22:05.597707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '099fd219f22d'
down_revision: Union[str, Sequence[str], None] = '634b4cbdd0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('audio_format', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_public_id'), 'voice', ['public_id'], unique=True)
    op.create_index(op.f('ix_voice_speaker_id'), 'voice', ['speaker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_speaker_id'), table_name='voice')
    op.drop_index(op.f('ix_voice_public_id'), table_name='voice')
    op.drop_table('voice')
    # ### end Alembic commands ###
