# type: ignore
# ruff: noqa
"""

Revision ID: 533ee7513528
Revises: 099fd219f22d
Create Date: 2026-01-12 15:27:07.831647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '533ee7513528'
down_revision: Union[str, Sequence[str], None] = '099fd219f22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False))
    op.add_column('speaker', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('speaker', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_speaker_public_id'), 'speaker', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_public_id'), table_name='speaker')
    op.drop_column('speaker', 'updated_at')
    op.drop_column('speaker', 'created_at')
    op.drop_column('speaker', 'public_id')
    # ### end Alembic commands ###
